### ISSUE TITLE
Update pkgdown documentation

### ISSUE THREAD

**Issue by sdhutchins** [vallenderlab/MicrobiomeR#15]
## ToDo

- [x] Add our custom pkgdown theme (https://github.com/vallenderlab/vallender-pkgdown-theme)
- [x] Add vignettes
- [x] Ensure changelog/news.md is added
- [x] Order functions into groups for the reference page i.e. data wrangling, visualization, utils etc.

## More ToDos via @grabear https://github.com/vallenderlab/MicrobiomeR/issues/15#issuecomment-451359295

- [x] Add an **About** tab on the navbar
  - [x] Add a [leaflet widget](https://pkgdown.r-lib.org/articles/test/widget.html)
- [ ] Add vignette's for shaurita's functions
  - [x] Stacked Bar
  - [ ] Ordination
  - [x] Permanova
  - [ ] Alpha Diversity
- [ ] Hunt down pkgdown warnings:
  - [ ]  ![image](https://user-images.githubusercontent.com/20953530/50675251-78652280-0fb2-11e9-909b-0aea6acbcf50.png)
  - [ ] ![image](https://user-images.githubusercontent.com/20953530/50675312-fc1f0f00-0fb2-11e9-80bb-b15fdad25b5e.png)
- [ ] Add [search](https://pkgdown.r-lib.org/articles/pkgdown.html#search)
- [ ] Look at some of the pkgdown articles to get any other ideas

**Comment by sdhutchins** [comment]
I think the test branch might be too messy to merge - I did a lot of weird things over there if I recall correctly (non pkgdown things)...

If you want I can do a quick pkgdown branch with just some of the base pkgdown things I implemented in the test branch.

**Comment by grabear** [comment]
That would be legit!

**Comment by sdhutchins** [comment]
Also, check out this package's pkgdown. Nice example imo.

https://valr.hesselberthlab.org/index.html

**Comment by grabear** [comment]
Do you know if there is a quicker way to build the reference based on the roxygen tag `@family`?? @sdhutchins 

That's what I'm going to do anyway, but I can't find anything in the docs (so far).

**Comment by sdhutchins** [comment]
Yes, check out this link: https://pkgdown.r-lib.org/reference/build_reference.html

**Comment by sdhutchins** [comment]
![image](https://user-images.githubusercontent.com/20976111/50668813-2ce94f00-0f87-11e9-8de7-7f7a94498011.png)

**Comment by sdhutchins** [comment]
```yaml
reference:
- title: Data Visualization
  contents:
  - ends_with("_plot")
```

I don't know how helpful that will be....

**Comment by grabear** [comment]
Yea, I was hoping I could port all of the `@family Data Visualization` functions and make that a reference section, but it seems that `pkgdown` doesn't do that out of the box..

I filed an issue, so we should hopefully get some insight.  https://github.com/r-lib/pkgdown/issues/954

**Comment by sdhutchins** [comment]
Reference https://github.com/r-lib/pkgdown/issues/248 as well. Someone asked there.

**Comment by sdhutchins** [comment]
They made it where you can base it on the `@concept` tag.

**Comment by grabear** [comment]
So do we need to do that with roxygen? @sdhutchins

**Comment by sdhutchins** [comment]
> So do we need to do that with roxygen? @sdhutchins

Yeah, but it may be that it's easy enough to implement selecting by `@family` instead of us having to go back and add the `@concept` tag to all of our functions.

About the `@concept` tag:

> Aliases form the index that ? searches. Use @aliases space separated aliases to add additional aliases.
> 
> @concept add extra keywords that will be found with help.search()

**Comment by grabear** [comment]
Hrmmm...  I'm just going to use RStudio to get all of the functions with the family tag:

 **Edit** > **Find in Files** "@family"

It actually works nicely and it points out the inconsistencies in family names:

![image](https://user-images.githubusercontent.com/20953530/50669970-2c07eb80-0f8e-11e9-8dc0-34ce308485c9.png)

**Comment by sdhutchins** [comment]
Oh dear! lol Does work though!

**Comment by sdhutchins** [comment]
I bet there is a regex that lets you do this and you could build a function for it but....

**Comment by grabear** [comment]
More Todos:
------
- [ ] Add an **About** tab on the navbar
  - [ ] Add a [leaflet widget](https://pkgdown.r-lib.org/articles/test/widget.html)
- [ ] Add vignette's for shaurita's functions
  - [ ] Stacked Bar
  - [ ] Ordination
- [ ] Hunt down pkgdown warnings:
  - [ ]  ![image](https://user-images.githubusercontent.com/20953530/50675251-78652280-0fb2-11e9-909b-0aea6acbcf50.png)
  - [ ] ![image](https://user-images.githubusercontent.com/20953530/50675312-fc1f0f00-0fb2-11e9-80bb-b15fdad25b5e.png)
- [ ] Add [search](https://pkgdown.r-lib.org/articles/pkgdown.html#search)
- [ ] Look at some of the pkgdown articles to get any other ideas

**Comment by grabear** [comment]
Should I commit all of the `build_site()` files?  @sdhutchins

**Comment by sdhutchins** [comment]
> Should I commit all of the `build_site()` files? @sdhutchins

Yeah, go ahead and do so.

On the warnings, typically the `topic must be a valid R expression` means the function does not exist or there is no .rd file for it.

I don't know if pkgdown supports the pretty print tag. The seealso is self-explanatory.

**Comment by sdhutchins** [comment]
FYI @grabear 

This week, I'm going to try to add more in-depth documentation to the `alpha_diversity` and `ordination` functions. I'm also going to integrate the search box for our docs.
