### ISSUE TITLE
Add tests using testthat

### ISSUE THREAD

**Issue by sdhutchins** [vallenderlab/MicrobiomeR#49]
## References
`testthat` [docs](https://testthat.r-lib.org/reference/index.html)

Hadley's [breakdown](http://r-pkgs.had.co.nz/tests.html)

## ToDo

- [x] Add a test for ordination
- [x] Add a test for heat tree creation
- [x] Add a test for correlation plot creation
- [x] Add tests for formatting functions
- [x] Add tests for palettes
- [x] Add tests for utils (#61)
- [x] Add tests for phyloseq functions
- [x] test for `stacked_barplot`
- [x] test for `alpha_diversity_plot`
- [x] test for `permanova`
- [x] test for `get_alpha_diversity_measures` (1c3a7ae)

**Comment by sdhutchins** [comment]
Code coverage was at 74% in PR #67. This issue can be closed now.
